services:
  functionapptest:
    build:
      context: FunctionAppTest
      dockerfile: Dockerfile
    ports:
      - "8080:80"    
    depends_on:
       - db-functionapptest  
  db-functionapptest:
    build:
        context: Db
    ports:
        - 1433:1433